bert_gen:
  config_path: config.json
  device: cuda
  num_processes: 4
  use_multi_device: false
dataset_path: "Data/poki"
mirror: 'openi'
openi_token: 'eb9b666e42ced4d4bc4515fb8390eaf3b77ad0f1'
preprocess_text:
  clean: true
  cleaned_path: filelists/cleaned.list
  config_path: config.json
  max_val_total: 8
  train_path: filelists/train.list
  transcription_path: filelists/short_character_anno.list
  val_path: filelists/val.list
  val_per_spk: 4
resample: 
  in_dir: audios/raw
  out_dir: audios/wavs
  sampling_rate: 44100
server:
  device: cuda
  models:
  - config: ./Data/poki/config.json
    device: cuda
    language: EN
    model: ./Data/poki/models/G_30000.pth
    speakers:
    - length_scale: 1.2
      noise_scale: 0.6
      noise_scale_w: 0.8
      sdp_ratio: 1.0
      speaker: "poki"
  port: 28000 
train_ms:
  base:
    model_image: "Bert-VITS2中日英底模-fix"
    repo_id: Stardust_minus/Bert-VITS2
    use_base_model: true
  config_path: config.json
  env:
    MASTER_ADDR: localhost
    MASTER_PORT: 28000
    RANK: 0
    THE_ENV_VAR_YOU_NEED_TO_USE: '1234567'
    WORLD_SIZE: 1
  model: models
translate:
  app_key: ''
  secret_key: ''
webui:
  config_path: Data/ying/config.json
  debug: false
  device: cuda
  language_identification_library: langid
  model: models/G_4600.pth
  port: 28000
  share: false
